### PR TITLE
Added Spark-GPU example

### PR DESCRIPTION
**Pull request by skandtandon**

### CODE REVIEW

**Comment by azubkov-swe** [comment]
hey @skandtandon -- the title is "**Added** Spark-GPU example", however there're only removing of files.

**Comment by skandtandon** [comment]
Hey @azubkov-swe, please check now. I have pushed that commit.

**Comment by skandtandon** [comment]
Added the Python GPU example and updated the README file.

**Review by prasadadireddi — APPROVED** [review]
lgtm

**Pull request merged**
