### PR TITLE
Spark vers mod

### PR DESCRIPTION
**Pull request by Sourabh0511**
Provide a clear and concise description of the content changes you're proposing. List all the changes you are making
to the content.

- Updated section the spark image version.

Reviewer's Tasks (for maintainers reviewing this PR):

- [ ] Verify that the tutorial functions correctly in a live environment.
- [ ] Verify that the updated content aligns with the [style guide](https://github.com/HPEEzmeral/ezua-tutorials/blob/develop/CONTRIBUTING.md#style-guide)
      in the contribution guidelines.
- [ ] Check for consistency, grammar, and clarity throughout the updated content.
- [ ] Check that the related GitHub issue is up-to-date.

### CODE REVIEW

**Comment by Sourabh0511** [comment]
Made appropriate changes.

**Review by akravacyber — APPROVED** [review]

**Comment by prasadadireddi** [comment]
@akravacyber There was discussion about these example Spark images with @skandtandon , believe he is working on generic solution to make spark image common to both mnist and ft examples.

@skandtandon can you comment here ?

**Comment by skandtandon** [comment]
Yeah @prasadadireddi as discussed with the spark team we would be dropping the use of special images for examples as we have a ezua-tutorial folder already mounted in shared-volume. As well as we will only be keeping the latest spark based examples in this case 3.5.0

**Comment by akravacyber** [comment]
Yes, it will be fine to use jars from shared volume. Okay, I'll be waiting for the PR, @skandtandon please let me know

**Comment by ask664** [comment]
@Sourabh0511  are we good to merge?

**Comment by Sourabh0511** [comment]
Yes I think so.

**Comment by akravacyber** [comment]
Closed as far as I've included all these changes in PR #112, which is merged now

**Pull request closed without merging**
