### PR TITLE
EZAF-5374 Update Ray Tune example

### PR DESCRIPTION
**Pull request by Manish-2023**
**Ray is updated to v2.24.0**

- Replaced hyperparameter example with independent trials for Ray Tune
- Added error handling for all examples

Checklist:

- [x] I have checked that my enhancements are not duplicates of existing content changes or additions.
- [ ] I have tested the changes in a working environment to ensure they function as intended.
- [x] I have followed the [style guide](https://github.com/HPEEzmeral/ezua-tutorials/blob/develop/CONTRIBUTING.md#style-guide)
      outlined in the contribution guidelines.

Reviewer's Tasks (for maintainers reviewing this PR):

- [ ] Verify that the tutorial functions correctly in a live environment.
- [ ] Verify that the updated content aligns with the [style guide](https://github.com/HPEEzmeral/ezua-tutorials/blob/develop/CONTRIBUTING.md#style-guide)
      in the contribution guidelines.
- [ ] Check for consistency, grammar, and clarity throughout the updated content.
- [ ] Check that the related GitHub issue is up-to-date.

### CODE REVIEW

**Review by sercanCyberVision — APPROVED** [review]
Thanks @Manish-2023, LGTM!

**Review by ask664 — APPROVED** [review]

**Comment by ask664** [comment]
Is it good to merge?

**Review by Bhargavjd — APPROVED** [review]
LGTM

**Comment by Manish-2023** [comment]
> Is it good to merge?

Yes

**Pull request merged**
