### PR TITLE
Enhance Spark jobs for Airflow

### PR DESCRIPTION
**Pull request by akravacyber**

### CODE REVIEW

**Comment by ask664** [comment]
@akravacyber update?

**Comment by akravacyber** [comment]
@ask664 Tested, ready to merge, https://github.com/HPEEzmeral/ezua-tutorials/pull/104 can be closed, because my PR is based on top od Saurabh changes

**Comment by akravacyber** [comment]
> @akravacyber update?

I will update this PR after #112 will be merged. It is more about updating spark sources, Airflow PR has got these changes in images

**Comment by akravacyber** [comment]
@ask664 it is ready to review and merdge

**Review by ask664 — APPROVED** [review]

**Review by ask664 — APPROVED** [review]

**Pull request merged**
