### PR TITLE
EZAF-4786: Ray Serve - Add a basic example to EZUA tutorials

### PR DESCRIPTION
**Pull request by sercanCyberVision**
**MOTIVATION**
With the `FY24-Q2` release, support for Ray Serve will be included. So, it is important to provide our end users with comprehensive instructions on its utilization. 

**SOLUTION**
The example in this PR demonstrates developing a machine learning model to predict rental prices, evaluating its performance, and deploying it for real-time inference using Ray Serve.

**EXECUTION**
1. Data and Model Management
3_plotting_model

2. Application Deployment
ray_dashboard_serve

3. Request Predictions:
8_prediction

### CODE REVIEW

**Comment by sercanCyberVision** [comment]
@Manish-2004, please execute and verify the example on your end.

**Review by prasadadireddi — APPROVED** [review]
lgtm

**Review by Manish-2004 — APPROVED** [review]
Validated with the updated notebook image!

**Comment by sercanCyberVision** [comment]
@ask664, can we merge this?

**Pull request merged**
