### PR TITLE
EZAF-6164 Update serving url in bike-sharing example

### PR DESCRIPTION
**Pull request by umka1332**
We have changed domain-template for KServe InferenceService url, so now it has only 1 subdomain. This was requested to enable usage of SSL certificates with one wildcard for subdomin (*.my-domain.com).

Provide a clear and concise description of the content changes you're proposing. List all the changes you are making
to the content.

### CODE REVIEW

**Comment by prasadadireddi** [comment]
I think target should be next patch or release ? I know the branch isn't created yet
@ask664 Can you create a q3-p1 branch from previous latest ?

**Comment by ask664** [comment]
https://github.com/HPEEzmeral/ezua-tutorials/tree/feature/fy24-q3-p1

CC - @prasadadireddi  @umka1332

**Comment by ask664** [comment]
FYR - https://github.hpe.com/hpe/ezaf/pull/2990

**Review by CybervisionVolodymyrPogorelov — APPROVED** [review]

**Comment by CybervisionVolodymyrPogorelov** [comment]
LGTM!

**Comment by umka1332** [comment]
Base was changed to https://github.com/HPEEzmeral/ezua-tutorials/tree/feature/fy24-q3-p1
Thanks @ask664 for creating it.

**Review by prasadadireddi — APPROVED** [review]
lgtm

**Review by ask664 — APPROVED** [review]

**Pull request merged**
